### ISSUE TITLE
请问你们打算什么时候公开代码呢

### ISSUE THREAD

**Issue by dingsiyu** [cooelf/SemBERT#1]
>

**Comment by Foehnc** [comment]
同问

**Comment by cooelf** [comment]
感谢关注！我们近期会整理代码，预计在12月中上旬的样子公开。

**Comment by cmxcn** [comment]
请问下会有对应的中文预训练模型发布吗？

**Comment by cooelf** [comment]
抱歉我们暂无提供中文模型的计划，需要替换SRL模型（以AllenNLP为例）：
1. 用AllenNLP训练中文SRL模型
2. 将AllenNLP中spaCy POS标注器换成中文模型 （https://github.com/allenai/allennlp/issues/2050）
