### ISSUE TITLE
 Why is the SRL information not used as an additional embedding layer.

### ISSUE THREAD

**Issue by Wenwen717** [cooelf/SemBERT#17]
First of all, thank you for being open source！
It isn't clear to me why the info of SRL is not used as additional embedding layers but is rather aggregated separately. Have you tried it before?
Hope you can share your opinion, thank you very much!

**Comment by cooelf** [comment]
Hi, I did not try it. Just think that revising the internal embedding layer might influence the parameter structure of the pre-trained BERT. Anyway, it is a good attempt when having time.

**Comment by Wenwen717** [comment]
Okay, thank you for your reply!!!
