### ISSUE TITLE
Error: online data annotation

### ISSUE THREAD

**Issue by Wangpeiyi9979** [cooelf/SemBERT#18]
你好，我想使用bert_srl进行srl标注，因此我下载了您给定的链接，下载下来后，里面有3个文件
`config.json  vocabulary/  weights.th
`
我将这3个文件放在一个文件夹bert_srl下，路径为xxx/xxx/bert_srl

最后我在运行run_classifier.py时加入--tagger_path xxx/xxx/bert_srl
可是却得到
`allennlp.common.checks.ConfigurationError: srl_bert is not a registered name for Model. You probably..`
这样的错误，请问具体应该怎么操作呢

**Comment by cooelf** [comment]
你好 allennlp相关的问题可以参考对应仓库的issues  我之前用的是elmo的版本，印象中也遇到过这个问题，可能跟allennlp或models的版本有关
