### ISSUE TITLE
forward计算中只用了cls，所以bert后的cnn对齐还有必要吗？另外请教是否尝试过融入词性特征呢？

### ISSUE THREAD

**Issue by jkkl** [cooelf/SemBERT#21]
first_token_tensor = sequence_output[:, 0]

**Comment by cooelf** [comment]
The alignment would be useful for improving the local interactions between the adjacent tokens. 
I simply concatenated them with the token embeddings, but did not see obvious improvements.

**Comment by jkkl** [comment]
@cooelf Thanks for your Reply。In my scenario，compared to bert-base-chinese, it has improved by abount 5 points.
