### ISSUE TITLE
Use pre-trained SemBERT as a sentence encoder?

### ISSUE THREAD

**Issue by drussellmrichie** [cooelf/SemBERT#24]
Hi, thanks for writing this very interesting paper and for providing this nice GitHub repo. :smile: I was wondering if it's possible -- and more to the point, straightforward! -- to use a SemBERT that you have trained to just get a sentence representation, which I can then use in my own neural network for classification or regression? I have a classification (or maybe ordinal regression...) task for which SRL features might be useful over and above BERT.

**Comment by cooelf** [comment]
Yes, in our tasks, SemBERT is actually used as the sentence encoder for classification and regression.
