### ISSUE TITLE
allennlp-models version

### ISSUE THREAD

**Issue by mirackk** [cooelf/SemBERT#27]
您好我能问一下allennlp-models 适配的版本吗
pytorch=1.0.0，allennlp=0.8.1

**Comment by cooelf** [comment]
你好，根据[之前相关issues](https://github.com/cooelf/SemBERT/issues/15)讨论的时间，可以试下安装2020年发布的allennlp-models的版本应该能work。

**Comment by mirackk** [comment]
已解决，感谢
