### ISSUE TITLE
Accuracy get from running the code is far less than in the paper

### ISSUE THREAD

**Issue by amyzhw** [cooelf/SemBERT#4]
Hi,
The acc on MNLI is reported as 84.0 for SemBERT_base.
However, I can only get 33.3 from running the code without any modification.

Could you let me know if I missed anything?

Thanks much,
Amy

**Comment by cooelf** [comment]
Please check if you used the sample data in the folder `glue_data/MNLI`, which is just used as example. 

You may annotate the semantic role labels using the tools following the instructions (especially for your own data)

or download our labeled data (for GLUE tasks) here for quick start.
https://drive.google.com/file/d/1B-_IRWRvR67eLdvT6bM0b2OiyvySkO-x/view?usp=sharing
