### ISSUE TITLE
- ERROR - pytorch_pretrained_bert.tokenization -   Model name 'bert-wwm-uncased' was not found in model name list 

### ISSUE THREAD

**Issue by Wenwen717** [cooelf/SemBERT#8]
报错说没有bert-wwm-uncased，麻烦大佬给解答下，谢谢

**Comment by cooelf** [comment]
这个仓库用的是早期的pytorch_pretrained_bert仓库，没有直接提供bert-wwm-uncased，可以参考transformers仓库下载这个模型，通过参数加载 --bert_model

**Comment by Wenwen717** [comment]
哦哦 好的  谢谢大佬！

**Comment by liamwazherealso** [comment]
@cooelf  @ColaXww Could either of you specify the location of the model? I've done a search but couldn't find the one use.

**Comment by Beam-coder** [comment]
@cooelf @LinMu7177 Hello, did you solve this problem? Is bert-wwm-uncased a model on Hugging Face? Is it for English? I can't find this model.
